-- MySQL Script generated by MySQL Workbench
-- lun 24 sep 2018 16:36:25 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TiendaMusica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TiendaMusica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TiendaMusica` ;
USE `TiendaMusica` ;

-- -----------------------------------------------------
-- Table `TiendaMusica`.`Artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TiendaMusica`.`Artista` ;

CREATE TABLE IF NOT EXISTS `TiendaMusica`.`Artista` (
  `IDArtista` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`IDArtista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `TiendaMusica`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TiendaMusica`.`Genero` ;

CREATE TABLE IF NOT EXISTS `TiendaMusica`.`Genero` (
  `IDGenero` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`IDGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TiendaMusica`.`Albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TiendaMusica`.`Albums` ;

CREATE TABLE IF NOT EXISTS `TiendaMusica`.`Albums` (
  `IDAlbum` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `IDArtista` INT NOT NULL,
  `IDGenero` INT NOT NULL,
  `Anio` INT NULL,
  PRIMARY KEY (`IDAlbum`),
  CONSTRAINT `fk_Albums_Artista`
    FOREIGN KEY (`IDArtista`)
    REFERENCES `TiendaMusica`.`Artista` (`IDArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Albums_Genero1`
    FOREIGN KEY (`IDGenero`)
    REFERENCES `TiendaMusica`.`Genero` (`IDGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Albums_Artista_idx` ON `TiendaMusica`.`Albums` (`IDArtista` ASC) VISIBLE;

CREATE INDEX `fk_Albums_Genero1_idx` ON `TiendaMusica`.`Albums` (`IDGenero` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
